// <auto-generated />
namespace VotoElectronico.AccesoDatos.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class indicesEscanioEleccionNombreOrden : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(indicesEscanioEleccionNombreOrden));
        
        string IMigrationMetadata.Id
        {
            get { return "202012261844163_indicesEscanioEleccionNombreOrden"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
