// <auto-generated />
namespace VotoElectronico.AccesoDatos.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class AuditoriaATablasListaYCandidato1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AuditoriaATablasListaYCandidato1));
        
        string IMigrationMetadata.Id
        {
            get { return "202008290237196_AuditoriaATablasListaYCandidato1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
